### ISSUE TITLE
返回 zk 映射后的那里处理的时候不是很好，建议完善一下

### ISSUE THREAD

**Issue by gaecoli** [peng128/pyhiveConnection#1]
在 zk 返回 result 后的代码并不是一定可以拿到 host 和 port，很可能就会返回 None

**Comment by xxzuo** [comment]
你可以把 hiveConnector.py 里面
这一行
`map(lambda x: resultHost.setdefault(x.split("=")[0], x.split("=")[1]), str(result[i]).split(";"))`
改成
`list(map(lambda x: resultHost.setdefault(x.split("=")[0], x.split("=")[1]), str(result[i]).split(";")))`

https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists
> [map()](https://docs.python.org/3.0/library/functions.html#map) and [filter()](https://docs.python.org/3.0/library/functions.html#filter) return iterators. If you really need a list, a quick fix is e.g. list(map(...)), but a better fix is often to use a list comprehension (especially when the original code uses [lambda](https://docs.python.org/3.0/reference/expressions.html#lambda)), or rewriting the code so it doesn’t need a list at all. Particularly tricky is [map()](https://docs.python.org/3.0/library/functions.html#map) invoked [for](https://docs.python.org/3.0/reference/compound_stmts.html#for) the side effects of the function; the correct transformation is to use a regular for loop (since creating a list would just be wasteful).

**Comment by gaecoli** [comment]
好的，我试试，感谢！
